### ISSUE TITLE
Demo Order

### ISSUE THREAD

**Issue by briank84** [UltraCart/my_account#14]
Cannot create a demo order.

http://demo.ultracartstore.com/cgi-bin/UCEditor?merchantId=DEMO&ADD=BASEBALL

The page doesn't load.

**Comment by perrytew** [comment]
Sorry for the delay in response.  The DEMO account is quite often being destroyed and recreated by people testing out the site features.  It's currently down because the theme was deleted by someone.  

We're going to search and update the url above and look to replace it with a more reliable merchant account for testing.  

Thanks.
